package pl.marcinchwedczuk.elfviewer.elfreader.elf.shared.notes;

import pl.marcinchwedczuk.elfviewer.elfreader.meta.ElfApi;
import pl.marcinchwedczuk.elfviewer.elfreader.utils.IntPartialEnum;

import java.util.Collection;
import java.util.Map;
import java.util.concurrent.atomic.AtomicReference;

/**
 * Applicable to notes with name = "GNU".
 */
public class ElfNoteTypeGnu extends IntPartialEnum<ElfNoteTypeGnu> {
    private static final Map<Integer, ElfNoteTypeGnu> byValue = mkByValueMap();
    private static final Map<String, ElfNoteTypeGnu> byName = mkByNameMap();

    /**
     * Operating system (OS) ABI information.  The
     * descriptor field will be 4 words:
     * <p>
     * <ul>
     *  <li>word 0: OS descriptor (ELF_NOTE_OS_LINUX, ELF_NOTE_OS_GNU, and so on)</li>
     *  <li>word 1: major version of the ABI</li>
     *  <li>word 2: minor version of the ABI</li>
     *  <li>word 3: subminor version of the ABI</li>
     * </ul>
     */
    @ElfApi("NT_GNU_ABI_TAG")
    public static final ElfNoteTypeGnu GNU_ABI_TAG = new ElfNoteTypeGnu(1, "GNU_ABI_TAG");

    /**
     * Synthetic hwcap information.  The desc field
     * begins with two words:
     * <p>
     * <ul>
     *  <li>word 0: number of entries</li>
     *  <li>word 1: bit mask of enabled entries</li>
     * </ul>
     * <p>
     * Then follow variable-length entries, one byte
     * followed by a null-terminated hwcap name
     * string.  The byte gives the bit number to test
     * if enabled, (1U << bit) & bit mask.
     */
    @ElfApi("NT_GNU_HWCAP")
    public static final ElfNoteTypeGnu GNU_HWCAP = new ElfNoteTypeGnu(2, "GNU_HWCAP");

    /**
     * Unique build ID as generated by the GNU ld(1)
     * --build-id option.  The desc consists of any
     * nonzero number of bytes.
     */
    @ElfApi("NT_GNU_BUILD_ID")
    public static final ElfNoteTypeGnu GNU_BUILD_ID = new ElfNoteTypeGnu(3, "GNU_BUILD_ID");

    /**
     * The desc contains the GNU Gold linker version
     * used.
     */
    @ElfApi("NT_GNU_GOLD_VERSION")
    public static final ElfNoteTypeGnu GNU_GOLD_VERSION = new ElfNoteTypeGnu(4, "GNU_GOLD_VERSION");

    @ElfApi("GNU_PROPERTY_TYPE_0")
    public static final ElfNoteTypeGnu GNU_PROPERTY_TYPE_0 = new ElfNoteTypeGnu(5, "GNU_PROPERTY_TYPE_0");

    protected ElfNoteTypeGnu(int value) {
        super(value);
    }

    protected ElfNoteTypeGnu(int value, String name) {
        super(value, name, byValue, byName);
    }

    public static ElfNoteTypeGnu fromValue(int value) {
        return IntPartialEnum.fromValueOrCreate(value, byValue, ElfNoteTypeGnu::new);
    }

    public static ElfNoteTypeGnu fromName(String name) {
        return IntPartialEnum.fromName(name, byName);
    }

    public static Collection<ElfNoteTypeGnu> knownValues() {
        return IntPartialEnum.knownValues(byValue);
    }

    private static AtomicReference<Map<String, String>> name2apiNameMappingContainer = new AtomicReference<>(null);
    @Override
    protected AtomicReference<Map<String, String>> name2apiNameMappingContainer() {
        return name2apiNameMappingContainer;
    }
}
